projects:
  default:
    schema: examples/local/schema.graphql
    documents: examples/local/!(schema).graphql
    extensions:
      codegen:
        generates:
          examples/local/graphql.go:
            hooks:
              afterOneFileWrite: go fmt
            plugins:
              - dist/index.js
  rick:
    schema: https://rickandmortyapi.com/graphql/
    documents: examples/rickandmorty/document.graphql
    extensions:
      codegen:
        generates:
          examples/rickandmorty/graphql.go:
            hooks:
              afterOneFileWrite: go fmt
            plugins:
              - dist/index.js:
                  packageName: rickandmorty
