name: CI/CD

on:
  push:
    paths-ignore:
      - README.md
      - .gitignore
      - .prettierignore
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and test
        run: |
          yarn
          yarn run build
          yarn run codegen
          yarn run test
